import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { Supplement } from '@/lib/db/schema';

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2 solid #44B080',
    paddingBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#1a1a1a',
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
  },
  supplementSection: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#F9F9F9',
    borderRadius: 5,
  },
  supplementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  supplementName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  supplementWhen: {
    fontSize: 10,
    padding: '4 8',
    backgroundColor: '#E5E5E5',
    borderRadius: 3,
    color: '#333',
  },
  supplementInfo: {
    marginTop: 8,
    paddingTop: 8,
    borderTop: '1 solid #E0E0E0',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  infoLabel: {
    fontSize: 10,
    color: '#666666',
  },
  infoValue: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  benefits: {
    marginTop: 8,
    paddingTop: 8,
    borderTop: '1 solid #E0E0E0',
  },
  benefitsText: {
    fontSize: 10,
    color: '#333',
    lineHeight: 1.5,
  },
  note: {
    marginTop: 8,
    paddingTop: 8,
    borderTop: '1 solid #E0E0E0',
    fontSize: 10,
    color: '#666666',
    fontStyle: 'italic',
  },
  footer: {
    marginTop: 30,
    paddingTop: 15,
    borderTop: '1 solid #E0E0E0',
    fontSize: 10,
    color: '#999999',
    textAlign: 'center',
  },
});

const whenToTakeLabels: Record<string, string> = {
  morning: 'Morning',
  afternoon: 'Afternoon',
  evening: 'Evening',
  before_meal: 'Before Meal',
  after_meal: 'After Meal',
  with_meal: 'With Meal',
  before_bed: 'Before Bed',
  as_needed: 'As Needed',
};

interface SupplementsPdfTemplateProps {
  clientName: string;
  supplements: Supplement[];
}

export function SupplementsPdfTemplate({ clientName, supplements }: SupplementsPdfTemplateProps) {
  if (supplements.length === 0) {
    return null;
  }

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Supplements Plan</Text>
          <Text style={styles.subtitle}>Prepared for: {clientName}</Text>
          <Text style={styles.subtitle}>
            Generated on: {new Date().toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </Text>
        </View>

        {supplements.map((supplement, index) => (
          <View key={supplement.id} style={styles.supplementSection} break={index > 0 && index % 4 === 0}>
            <View style={styles.supplementHeader}>
              <Text style={styles.supplementName}>{supplement.name}</Text>
              <View style={styles.supplementWhen}>
                <Text>{whenToTakeLabels[supplement.whenToTake] || supplement.whenToTake}</Text>
              </View>
            </View>

            <View style={styles.supplementInfo}>
              <View style={styles.infoRow}>
                <Text style={styles.infoLabel}>Pills per Dose:</Text>
                <Text style={styles.infoValue}>{supplement.pillsPerDose} pill{supplement.pillsPerDose !== 1 ? 's' : ''}</Text>
              </View>
              {supplement.dosage && (
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Dosage:</Text>
                  <Text style={styles.infoValue}>{supplement.dosage}</Text>
                </View>
              )}
            </View>

            <View style={styles.benefits}>
              <Text style={styles.benefitsText}>
                <Text style={{ fontWeight: 'bold' }}>Benefits: </Text>
                {supplement.benefits}
              </Text>
            </View>

            {supplement.note && (
              <View style={styles.note}>
                <Text>Note: {supplement.note}</Text>
              </View>
            )}
          </View>
        ))}

        <View style={styles.footer}>
          <Text>This supplements plan was generated by CoachFlow</Text>
        </View>
      </Page>
    </Document>
  );
}

